services:

  ## May change dbs to auto-scaling kubernetes instances ##
  # SQL Server instance for patients
  patient-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure    
    healthcheck:          
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # SQL Server instance for measurements
  measurement-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure    
    healthcheck:          
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # Patient-service - scaled to 2 replicas for X-axis scaling
  patient-service:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - "49152-49153:8080"
    environment:
      ConnectionStrings__PatientDb: "Server=patient-db;Database=PatientDb;User Id=sa;Password=YourStrong@Password;"
    deploy:
      replicas: 2  
    depends_on:
      - patient-db
    networks:
      app-network:
        aliases:
          - patient-service

# Measurement-service - scaled to 2 replicas for X-axis scaling
  measurement-service:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports:
      - "49162-49163:8080"
    deploy:
      replicas: 2
    depends_on:
      - measurement-db
    networks:
      app-network:
        aliases:
          - measurement-service
    
    
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5001:8080"
    deploy:
      # replicas: 2  # Two replicas for x-axis scaling
      restart_policy:
        condition: on-failure
    networks:
      - app-network
        
  # Adding Seq for logging
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341 # Exposing Seq on localhost:534
      - 5342:80 # Exposing Seq on localhost:5341
    environment:
      ACCEPT_EULA: Y


  # Adding Zipkin for tracing
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411 # Exposing Zipkin on localhost:9411



networks:
  app-network:
    driver: bridge
    



    