version: '3.9'

services:
  ## Patient Database for Region Zealand
  patient-db-region-zealand:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g        
          cpus: "1.0"       
        reservations:
          memory: 512m      
          cpus: "0.5"      
    networks:
      - app-network

  ## Patient Database for Region Midtjylland
  patient-db-region-midtjylland:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
        reservations:
          memory: 512m
          cpus: "0.5"
    networks:
      - app-network

  ## Patient Database for Region Nordjylland
  patient-db-region-nordjylland:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
        reservations:
          memory: 512m
          cpus: "0.5"
    networks:
      - app-network

  ## Patient Database for Region Syddanmark
  patient-db-region-syddanmark:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
        reservations:
          memory: 512m
          cpus: "0.5"
    networks:
      - app-network

  ## Patient Service for Region Zealand
  patient-service-region-zealand:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      REGION_CODE: "Zealand"
      ConnectionStrings__PatientDatabase: "Server=patient-db-region-zealand;Database=PatientDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;TrustServerCertificate=True;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - patient-db-region-zealand
    networks:
      app-network:
        aliases:
          - patient-service-region-zealand

  ## Patient Service for Region Midtjylland
  patient-service-region-midtjylland:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      REGION_CODE: "Midtjylland"
      ConnectionStrings__PatientDatabase: "Server=patient-db-region-midtjylland;Database=PatientDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;TrustServerCertificate=True;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - patient-db-region-midtjylland
    networks:
      app-network:
        aliases:
          - patient-service-region-midtjylland

  ## Patient Service for Region Nordjylland
  patient-service-region-nordjylland:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      REGION_CODE: "Nordjylland"
      ConnectionStrings__PatientDatabase: "Server=patient-db-region-nordjylland;Database=PatientDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;TrustServerCertificate=True;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - patient-db-region-nordjylland
    networks:
      app-network:
        aliases:
          - patient-service-region-nordjylland

  ## Patient Service for Region Syddanmark
  patient-service-region-syddanmark:
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      REGION_CODE: "Syddanmark"
      ConnectionStrings__PatientDatabase: "Server=patient-db-region-syddanmark;Database=PatientDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;TrustServerCertificate=True;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - patient-db-region-syddanmark
    networks:
      app-network:
        aliases:
          - patient-service-region-syddanmark

  ## Measurement Database for Region Zealand
  measurement-db-region-zealand:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  ## Measurement Database for Region Midtjylland
  measurement-db-region-midtjylland:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
        reservations:
          memory: 512m
          cpus: "0.5"
    networks:
      - app-network

  ## Measurement Database for Region Nordjylland
  measurement-db-region-nordjylland:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
        reservations:
          memory: 512m
          cpus: "0.5"
    networks:
      - app-network

  ## Measurement Database for Region Syddanmark
  measurement-db-region-syddanmark:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'SuperSecret7!' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"
        reservations:
          memory: 512m
          cpus: "0.5"
    networks:
      - app-network

  ## Measurement Service for Region Zealand
  measurement-service-region-zealand:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    environment:
      REGION_CODE: "Zealand"
      ConnectionStrings__MeasurementDatabase: "Server=measurement-db-region-zealand;Database=MeasurementDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - measurement-db-region-zealand
    networks:
      app-network:
        aliases:
          - measurement-service-region-zealand

  ## Measurement Service for Region Midtjylland
  measurement-service-region-midtjylland:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    environment:
      REGION_CODE: "Midtjylland"
      ConnectionStrings__MeasurementDatabase: "Server=measurement-db-region-midtjylland;Database=MeasurementDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - measurement-db-region-midtjylland
    networks:
      app-network:
        aliases:
          - measurement-service-region-midtjylland

  ## Measurement Service for Region Nordjylland
  measurement-service-region-nordjylland:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    environment:
      REGION_CODE: "Nordjylland"
      ConnectionStrings__MeasurementDatabase: "Server=measurement-db-region-nordjylland;Database=MeasurementDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - measurement-db-region-nordjylland
    networks:
      app-network:
        aliases:
          - measurement-service-region-nordjylland

  ## Measurement Service for Region Syddanmark
  measurement-service-region-syddanmark:
    build:
      context: .
      dockerfile: MeasurementService/Dockerfile
    environment:
      REGION_CODE: "Syddanmark"
      ConnectionStrings__MeasurementDatabase: "Server=measurement-db-region-syddanmark;Database=MeasurementDb;User Id=sa;Password=SuperSecret7!;Encrypt=false;"
    deploy:
      replicas: 2 # X-axis scaling
    depends_on:
      - measurement-db-region-syddanmark
    networks:
      app-network:
        aliases:
          - measurement-service-region-syddanmark

  ## API Gateway
  apigateway:
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - app-network

        
  # Adding Seq for logging
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341 # Exposing Seq on localhost:5341
      - 5342:80 # Exposing Seq on localhost:5342
    environment:
      ACCEPT_EULA: Y


  # Adding Zipkin for tracing
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411 # Exposing Zipkin on localhost:9411



networks:
  app-network:
    driver: bridge
