name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        shell: bash

      - name: Build Docker Images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t patient-service:latest -f PatientService/Dockerfile .
          docker build -t measurement-service:latest -f MeasurementService/Dockerfile .
          docker-compose up -d --build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Unit and Integration Tests
        run: |
              echo TODO - RUN TESTS

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        shell: bash
        
      - name: Deploy to Environment (Just simulating to show scaling) 
        run: |
          echo docker-compose up -d --scale patient-service=2 --scale measurement-service=2
